version: 2.1

orbs:
  terraform: circleci/terraform@1.0.1

jobs:
  terraform:
    name: 'Terraform'
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/src

workflows:
  terraform:
    jobs:
      - terraform
